### ISSUE TITLE
2.1 and 3.0 templates are not updated

### ISSUE THREAD

**Issue by wli3** [bozturkMSFT/insertions-client#10]
![image](https://user-images.githubusercontent.com/6993335/76671509-f7a99b00-6553-11ea-91ee-cbadae3e3f68.png)

**Comment by bozturkMSFT** [comment]
If you are using the sample ignored.txt file, those are not updated because they are requested to be ignored.
Nick mentioned that there were some issues with inserting them. That's why old versions of templates are in ignored.txt file.

**Comment by bozturkMSFT** [comment]
We have decided to remove templating related lines from ignored.txt file @donJoseLuis .

**Comment by donJoseLuis** [comment]
@bozturkMSFT is this a bug or a case of items configured to be ignored; which the tool ignores in turn?
- I'm unsure what exactly is required in this issue, perhaps I'm missing context from live conversations.

**Comment by donJoseLuis** [comment]
**issue summary**:

- folks in the .net user ux team have a common set of items to exclude which do not vary
- the request is to not require the preparation of an ignored.txt for these cases & simply exclude the items that follow...

Microsoft.VisualStudio.LiveShare
System.Reflection.Metadata
VS.ExternalAPIs.MSBuild
VS.Tools.Net.Core.SDK.Resolver
VS.Tools.Net.Core.SDK.x86
