### ISSUE TITLE
Bug Bash: cmd line tool help out of sync with Readme

### ISSUE THREAD

**Issue by donJoseLuis** [bozturkMSFT/insertions-client#19]
The parameters in the cmd line tool help are not up to date with the ReadMe; which describes newer parameters.

expected behavior:
both ReadMe & cmd line tool contain the same information, detailing the parameters the tool accepts

![insertion-client-help](https://user-images.githubusercontent.com/58810449/79754171-662e0580-8317-11ea-9d99-747a9dd17252.png)

![insertion-client-readme](https://user-images.githubusercontent.com/58810449/79754199-71813100-8317-11ea-9d4b-549e8756b9a6.png)

**Comment by ladipro** [comment]
Suggestion: use the square bracket notation to denote optional cmd line parameters. e.g.:

```
-m:<manifest.json full file path> [-i:<ignored packages file path>]
```

**Comment by ladipro** [comment]
Also, these warnings in the Readme are unsubstantiated:

```
NO SPACES ALLOWED IN EITHER default.config OR manifest.json FILE PATHS
NO SPACES ALLOWED IN props file search directory
```

The user can use (platform/shell specific) quotes on the command line to pass a string with spaces as one parameter. For Windows cmd for example:

```
InsertionsClient.exe -d:"Path with spaces\default.config"
```

**Comment by bozturkMSFT** [comment]
Tool help seems to have been updated in a [commit ](https://github.com/bozturkMSFT/insertions-client/pull/17/commits/0d3ffd467afc35231321c0a5145f26f239fb3d84) 3 days prior to creation of this ticket. I believe you forgot to build before testing.

Brackets for optional parameters are added in dcd6c232335ae2da3b2653881a65cd43bfcec79f.
