### ISSUE TITLE
Bug Bash: Empty Statistics output message

### ISSUE THREAD

**Issue by donJoseLuis** [bozturkMSFT/insertions-client#21]
20-4-2020 02:52:05.682962|thread:1|Saving modified config file: C:\GitHub\insertions-client\tests\InsertionsClientTest\Assets\default.config
20-4-2020 02:52:05.714238|thread:1|Save success.
20-4-2020 02:52:05.734160|thread:1|**Statistics:**

[log_637229911252339885.txt](https://github.com/bozturkMSFT/insertions-client/files/4504005/log_637229911252339885.txt)

**Comment by bozturkMSFT** [comment]
This is the correct behaviour. Statistical results are listed below that line https://github.com/bozturkMSFT/insertions-client/blob/df802e661803b76d692a9f27c676cccbd43ee329/src/InsertionsClient/Api/Providers/InsertionApi.cs#L119.

**Comment by donJoseLuis** [comment]
please instead of...

20-4-2020 04:19:58.841867|thread:1|Statistics:
20-4-2020 04:19:58.849247|thread:1|ExactMatch - Update for case of matching manifest.json assets with multiple verions; where version of the exact matching NuGet asset was selected

consider...
20-4-2020 04:19:58.841867|thread:1|Statistics:
ExactMatch - Update for case of matching manifest.json assets with multiple verions; where version of the exact matching NuGet asset was selected
…
...
